"""
DevLens AI — GitHub OAuth Routes
GET  /api/v1/auth/github/login    → redirect user to GitHub OAuth
GET  /api/v1/auth/github/callback → exchange code for token, upsert user
GET  /api/v1/auth/me              → get current authenticated user
DELETE /api/v1/auth/logout        → invalidate session (client clears token)
"""

import structlog
import httpx
from fastapi import APIRouter, Depends, HTTPException, Query, status
from fastapi.responses import RedirectResponse, JSONResponse, HTMLResponse
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from app.config import get_settings
from app.api.deps import get_db, get_current_user
from app.models.user import User
from app.schemas.session import UserResponse

logger = structlog.get_logger(__name__)
settings = get_settings()
router = APIRouter()

# ── GITHUB AUTH CONTROLLER ENDPOINT ───────────────────────────────────────
# (rest of code is unchanged, we will edit the callback return)

GITHUB_AUTH_URL = "https://github.com/login/oauth/authorize"
GITHUB_TOKEN_URL = "https://github.com/login/oauth/access_token"
GITHUB_USER_URL = "https://api.github.com/user"


# ── Step 1: Redirect to GitHub ─────────────────────────────────────────────

@router.get("/github/login")
async def github_login():
    """Redirect the browser to GitHub's OAuth consent page."""
    params = {
        "client_id": settings.github_client_id,
        "redirect_uri": settings.github_redirect_uri,
        "scope": "read:user repo",  # repo scope needed for private repos
    }
    query = "&".join(f"{k}={v}" for k, v in params.items())
    return RedirectResponse(url=f"{GITHUB_AUTH_URL}?{query}")


# ── Step 2: GitHub redirects back with ?code= ──────────────────────────────

@router.get("/github/callback")
async def github_callback(
    code: str = Query(..., description="OAuth code from GitHub"),
    db: AsyncSession = Depends(get_db),
):
    """
    Exchange the OAuth code for an access token.
    Upsert the GitHub user into our database.
    Return the user's DevLens API key to the frontend.
    """
    async with httpx.AsyncClient() as client:
        # Exchange code → access token
        token_resp = await client.post(
            GITHUB_TOKEN_URL,
            json={
                "client_id": settings.github_client_id,
                "client_secret": settings.github_client_secret,
                "code": code,
                "redirect_uri": settings.github_redirect_uri,
            },
            headers={"Accept": "application/json"},
            timeout=10,
        )
        token_data = token_resp.json()

        if "error" in token_data:
            logger.error("github_oauth_token_exchange_failed", error=token_data)
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail=f"GitHub OAuth error: {token_data.get('error_description', 'Unknown')}",
            )

        access_token = token_data["access_token"]

        # Fetch GitHub user profile
        user_resp = await client.get(
            GITHUB_USER_URL,
            headers={
                "Authorization": f"Bearer {access_token}",
                "Accept": "application/vnd.github.v3+json",
            },
            timeout=10,
        )
        gh_user = user_resp.json()

    # Upsert user in our DB
    result = await db.execute(
        select(User).where(User.github_id == gh_user["id"])
    )
    user = result.scalar_one_or_none()

    if user:
        # Update existing user's token and profile
        user.github_access_token = access_token
        user.github_username = gh_user["login"]
        user.github_name = gh_user.get("name")
        user.github_avatar_url = gh_user.get("avatar_url")
    else:
        # Create new user — api_key auto-generated by the model default
        user = User(
            github_id=gh_user["id"],
            github_username=gh_user["login"],
            github_name=gh_user.get("name"),
            github_avatar_url=gh_user.get("avatar_url"),
            github_access_token=access_token,
        )
        db.add(user)

    await db.commit()
    await db.refresh(user)

    import urllib.parse
    
    logger.info("user_authenticated", github_username=user.github_username)

    # Pass the session details back to the frontend via URL parameters
    # The frontend will read these, save them to its own localStorage, and clear the URL.
    params = {
        "token": user.api_key,
        "username": user.github_username,
        "avatar": user.github_avatar_url or "",
        "name": user.github_name or "",
    }
    query = urllib.parse.urlencode(params)
    redirect_url = f"{settings.frontend_url}?{query}"
    
    return RedirectResponse(url=redirect_url)


# ── Get current user ───────────────────────────────────────────────────────

@router.get("/me", response_model=UserResponse)
async def get_me(current_user: User | None = Depends(get_current_user)):
    """Return the currently authenticated user's profile."""
    if not current_user:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Not authenticated. Send X-Session-Token header.",
        )
    return current_user
